### ISSUE TITLE
Tries Counter does not work

### ISSUE THREAD

**Issue by Friday64** [Friday64/Brick_Breaker_Game#4] opened 2024-06-03 12:40 UTC

**Comment by JoshKoiro** [comment] 2024-06-03 16:01
Is this a duplicate of #3 ? We should close this as "not planned" if it is.

![image](https://github.com/Friday64/Brick_Breaker_Game/assets/16432071/c641de2f-660f-4568-800d-dbe756c193ce)

**Comment by Friday64** [comment] 2024-06-03 19:10
Yes, simple mistake

**Closed as not planned** 2024-06-03 19:10 UTC
